[package]
name = "bolt-types"
version = "0.2.4"
description = "Autogenerate types for the bolt language"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "bolt_types"

[dependencies]
bolt-lang.workspace = true
anchor-lang.workspace = true
