[package]
name = "bolt-types"
version = "0.1.4"
description = "Autogenerate types for the bolt language"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "bolt_types"

[dependencies]
bolt-lang = { path = "../../crates/bolt-lang" }
anchor-lang = { version = "0.30.1" }
