[package]
name = "bolt-types"
version = "0.1.6"
description = "Autogenerate types for the bolt language"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "bolt_types"

[dependencies]
bolt-lang = "0.1.6"
anchor-lang = "0.30.1"
